"""C12A — a DOCX paragraph locator points at a paragraph, or at nothing.

The claim under test is the one the card is really about: **a locator must
address something that exists.** Everything else here is arranged so that
statement can be made as strongly as possible — not "the text came back" but
``Document.paragraphs[n - 1]._p is <the element the fragment was taken from>``,
where ``Document.paragraphs`` is python-docx's own list and never sees this
parser's XML walk.

The documents are real ``.docx`` packages generated by
``evals/fixtures/docx/build_fixtures.py`` and committed under
``evals/fixtures/docx``. python-docx 1.2.0 (MIT) is a real library doing the
real OOXML work; nothing in this file is a stand-in.
"""

from __future__ import annotations

import uuid

import pytest
from docx import Document
from docx_fixtures import fixture_path

from kb.catalog.parsers.docx_archive import ArchiveLimits, DocxArchiveError
from kb.catalog.parsers.docx_parser import (
    MAX_TEXT_DEPTH,
    PARSER_NAME,
    PARSER_VERSION,
    parse_docx,
    parse_docx_bytes,
    resolve_locator,
)
from kb.contracts.entities import Locator
from kb.contracts.enums import LocatorKind

pytest_plugins = ["docx_fixtures"]
pytestmark = pytest.mark.integration

SOURCE = uuid.uuid5(uuid.NAMESPACE_URL, "kb-c12a-source")


def parse(name: str):
    return parse_docx(fixture_path(name), source_id=SOURCE)


def reopened(name: str) -> Document:
    """A second, independent handle on the same file."""
    return Document(str(fixture_path(name)))


# ================================================= the numbering rule itself


def test_paragraph_n_is_exactly_document_paragraphs_n_minus_one():
    """The one invariant every other assertion in this card leans on.

    ``paragraph=N`` is claimed to *be* ``Document.paragraphs[N-1]`` — the same
    XML element, not merely the same text. Identity is checked, not equality:
    a parser that shuffled its own counter while reproducing the text would pass
    an equality check and fail this one.
    """
    document = reopened("basic.docx")
    result = parse("basic.docx")
    paragraphs = [f for f in result.fragments if f.locator.kind is LocatorKind.DOCX_PARAGRAPH]
    assert paragraphs, "the fixture must produce paragraph fragments"
    for fragment in paragraphs:
        number = fragment.locator.paragraph
        resolved = resolve_locator(document, fragment.locator)
        assert resolved is not None
        assert document.paragraphs[number - 1]._p is resolved.element
        assert resolved.text == fragment.text


def test_a_blank_paragraph_consumes_a_number_and_produces_no_fragment():
    """The counter counts every ``w:p``, not every ``w:p`` that had text.

    ``basic.docx`` has an empty paragraph between body paragraphs 2 and 4. If
    the parser numbered only non-empty paragraphs, the third one would carry
    ``paragraph=3`` and every address after it would be off by one — a locator
    that points at a real paragraph, just not the one it claims.
    """
    document = reopened("basic.docx")
    assert document.paragraphs[2].text == "", "fixture precondition: body paragraph 3 is blank"
    numbers = [
        f.locator.paragraph
        for f in parse("basic.docx").fragments
        if f.locator.kind is LocatorKind.DOCX_PARAGRAPH
    ]
    assert numbers == [1, 2, 4, 5, 6]
    assert parse("basic.docx").counts.empty_paragraphs_skipped == 1


def test_a_locator_that_names_nothing_resolves_to_none_and_not_to_a_neighbour():
    """Out of range, wrong shape, wrong kind: ``None``, never a near miss."""
    document = reopened("basic.docx")
    beyond = Locator(kind=LocatorKind.DOCX_PARAGRAPH, paragraph=999)
    assert resolve_locator(document, beyond) is None
    shaped_wrong = Locator(kind=LocatorKind.DOCX_PARAGRAPH)
    assert resolve_locator(document, shaped_wrong) is None
    a_pdf = Locator(kind=LocatorKind.PDF_FILE_PAGE, file_page=1, paragraph=1)
    assert resolve_locator(document, a_pdf) is None
    beyond_table = Locator(kind=LocatorKind.DOCX_TABLE, table=7)
    assert resolve_locator(document, beyond_table) is None
    beyond_cell = Locator(kind=LocatorKind.DOCX_CELL, table=1, cell=(9, 9))
    assert resolve_locator(document, beyond_cell) is None


def test_a_cell_locator_without_a_table_number_resolves_to_nothing():
    document = reopened("basic.docx")
    assert resolve_locator(document, Locator(kind=LocatorKind.DOCX_CELL, cell=(1, 1))) is None
    assert resolve_locator(document, Locator(kind=LocatorKind.DOCX_CELL, table=1)) is None


# ==================================================== what a locator does not say


def test_no_docx_locator_carries_a_page_a_label_or_a_snapshot():
    """A DOCX has no page until something lays it out. This card does not.

    The temptation to fill ``file_page`` with "the page it would be on" is the
    exact failure the contract is built to prevent, so every field that would
    have to be guessed is asserted to be ``None`` on every fragment.
    """
    for name in ("basic.docx", "nested_table.docx", "merged_cells.docx", "exotic_runs.docx"):
        for fragment in parse(name).fragments:
            locator = fragment.locator
            assert locator.file_page is None, name
            assert locator.printed_label is None, name
            assert locator.spine is None, name
            assert locator.snapshot_url is None, name
            assert locator.snapshot_at is None, name


def test_the_contract_itself_refuses_a_printed_label_standing_in_for_a_page():
    """kb.contracts, not this parser, is where the rule is enforced — and it fires."""
    with pytest.raises(ValueError, match="not a file page"):
        Locator(kind=LocatorKind.PDF_PRINTED_LABEL, printed_label="xii", file_page=3)


def test_the_library_and_the_extractor_version_are_recorded_on_every_result():
    result = parse("basic.docx")
    assert result.parser == PARSER_NAME
    assert result.parser_version == PARSER_VERSION
    assert result.library == "python-docx"
    assert result.library_version == "1.2.0"
    assert result.archive.parts > 0


# ======================================================= headings and chapter


def test_a_fragment_is_filed_under_the_heading_it_sits_under():
    result = parse("basic.docx")
    by_number = {
        f.locator.paragraph: f
        for f in result.fragments
        if f.locator.kind is LocatorKind.DOCX_PARAGRAPH
    }
    assert by_number[1].locator.chapter == "Brand voice"
    assert by_number[2].locator.chapter == "Brand voice"
    assert by_number[4].locator.chapter == "Brand voice"
    assert by_number[5].text == "Colour"
    assert by_number[5].locator.chapter == "Colour"
    assert by_number[6].locator.chapter == "Colour"


def test_a_fragment_with_no_heading_above_it_says_none_rather_than_the_title():
    for name in ("nested_table.docx", "merged_cells.docx"):
        result = parse(name)
        assert all(f.locator.chapter is None for f in result.fragments), name


def test_a_table_and_its_cells_inherit_the_heading_in_scope_when_they_appear():
    result = parse("basic.docx")
    table = result.by_kind(LocatorKind.DOCX_TABLE)[0]
    assert table.locator.chapter == "Brand voice"
    assert all(f.locator.chapter == "Brand voice" for f in result.by_kind(LocatorKind.DOCX_CELL))


# =============================================== the constructs that get refused


def test_a_body_level_content_control_is_reported_with_its_text_and_no_locator():
    """Its paragraphs are not children of ``w:body``, so they are not numbered.

    They are also not dropped: the text comes back in the unsupported report, so
    a curator can see that something in this file was not turned into fragments
    and why.
    """
    result = parse("exotic_runs.docx")
    notes = [u for u in result.unsupported if u.code == "body_content_control"]
    assert len(notes) == 1
    assert "paragraph inside a body level control" in notes[0].text
    assert "not direct children of w:body" in notes[0].detail
    assert not any("body level control" in f.text for f in result.fragments)


def test_a_text_box_is_not_attributed_to_the_paragraph_that_anchors_it():
    result = parse("exotic_runs.docx")
    notes = [u for u in result.unsupported if u.code == "text_box"]
    assert len(notes) == 1
    assert notes[0].address == "paragraph 3"
    assert all("text box content" not in f.text for f in result.fragments)
    assert any("text box" not in f.text for f in result.fragments)


def test_tracked_deletion_is_excluded_from_the_text_and_reported():
    """Deleted text is not in the document; a tracked insertion is."""
    result = parse("exotic_runs.docx")
    paragraph_three = next(f for f in result.fragments if f.locator.paragraph == 3)
    assert "deleted text" not in paragraph_three.text
    assert "inserted text" in paragraph_three.text
    assert any(
        u.code == "tracked_deletion" and u.address == "paragraph 3" for u in result.unsupported
    )


def test_a_deleted_word_never_leaks_into_any_fragment_of_the_document():
    for fragment in parse("exotic_runs.docx").fragments:
        assert "deleted text" not in fragment.text


def test_a_field_result_is_read_once_and_its_instruction_never_is():
    """``mc:Choice`` and ``mc:Fallback`` hold the same content; reading both
    would print it twice. ``w:instrText`` is a code, not content."""
    result = parse("exotic_runs.docx")
    alternate = next(f for f in result.fragments if f.locator.paragraph == 4)
    assert alternate.text.count("CHOICE-BRANCH") == 1
    assert "FALLBACK-BRANCH" not in alternate.text
    exotic = next(f for f in result.fragments if f.locator.paragraph == 3)
    assert "PAGE" not in exotic.text.replace("hyperlink", "")
    assert exotic.text.count("7") == 1


def test_a_paragraph_nested_past_the_depth_limit_is_reported_not_half_read():
    """XML from an upload has no bound on nesting. The walk stops and says so.

    Without the guard this is a ``RecursionError`` in the middle of a parse. With
    it, the parser returns what it managed to read *and* a note naming the
    paragraph where it stopped — the difference between a document that was read
    and a document that was abandoned halfway.
    """
    result = parse_docx_bytes(_nested_paragraph_document(MAX_TEXT_DEPTH + 20), source_id=SOURCE)
    deep = next(f for f in result.fragments if f.locator.paragraph == 2)
    assert deep.text == "SHALLOW"
    assert "DEEP" not in deep.text
    notes = [u for u in result.unsupported if u.code == "text_depth_limit"]
    assert len(notes) == 1
    assert notes[0].address == "paragraph 2"
    assert str(MAX_TEXT_DEPTH) in notes[0].detail


def test_a_reasonable_nesting_depth_is_read_completely_and_reports_nothing():
    result = parse_docx_bytes(_nested_paragraph_document(4), source_id=SOURCE)
    deep = next(f for f in result.fragments if f.locator.paragraph == 2)
    assert deep.text == "SHALLOW DEEP"
    assert not [u for u in result.unsupported if u.code == "text_depth_limit"]


W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"


def _nested_paragraph_document(depth: int) -> bytes:
    """A genuinely valid package holding one paragraph nested ``depth`` levels.

    ``w:sdt`` inside ``w:sdtContent`` is real WordprocessingML, so this is a
    structure a real file can contain rather than an XML trick that only this
    parser would ever see. The paragraph also carries text at the top, so a
    truncated walk produces a fragment that is visibly incomplete rather than an
    absent one.
    """
    import io

    from docx import Document as _Document
    from lxml import etree

    wrapped = "<w:r><w:t>DEEP</w:t></w:r>"
    for _ in range(depth):
        wrapped = f"<w:sdt><w:sdtPr/><w:sdtContent>{wrapped}</w:sdtContent></w:sdt>"
    element = etree.fromstring(
        f'<w:p xmlns:w="{W_NS}"><w:r><w:t>SHALLOW </w:t></w:r>{wrapped}</w:p>'
    )

    document = _Document()
    document.add_paragraph("anchor")
    body = document.element.body
    body.insert(len(body) - 1, element)
    buffer = io.BytesIO()
    document.save(buffer)
    return buffer.getvalue()


# ============================================================== archive limits


def test_the_container_is_checked_before_a_single_part_is_inflated(tmp_path):
    limits = ArchiveLimits(max_file_bytes=1024)
    with pytest.raises(DocxArchiveError, match="limit is 1024"):
        parse_docx(fixture_path("basic.docx"), source_id=SOURCE, limits=limits)


def test_a_part_that_expands_far_past_its_compressed_size_is_refused(tmp_path):
    bomb = tmp_path / "bomb.docx"
    bomb.write_bytes(_zip_with_a_huge_part())
    with pytest.raises(DocxArchiveError, match="expands"):
        parse_docx(bomb, source_id=SOURCE)


def test_too_many_parts_is_refused(tmp_path):
    crowded = tmp_path / "crowded.docx"
    crowded.write_bytes(_zip_with_many_parts(20))
    with pytest.raises(DocxArchiveError, match="parts"):
        parse_docx(crowded, source_id=SOURCE, limits=ArchiveLimits(max_parts=10))


def test_a_container_with_no_word_document_part_is_refused(tmp_path):
    wrong = tmp_path / "wrong.docx"
    wrong.write_bytes(_zip_without_document_xml())
    with pytest.raises(DocxArchiveError, match=r"word/document\.xml"):
        parse_docx(wrong, source_id=SOURCE)


def test_a_member_name_that_escapes_the_container_is_refused(tmp_path):
    evading = tmp_path / "evading.docx"
    evading.write_bytes(_zip_with_a_traversing_member())
    with pytest.raises(DocxArchiveError, match="relative path"):
        parse_docx(evading, source_id=SOURCE)


def test_a_refused_container_yields_no_fragments_at_all(tmp_path):
    """A refusal is not a partial parse. There is no half-built result to keep."""
    bomb = tmp_path / "bomb2.docx"
    bomb.write_bytes(_zip_with_a_huge_part())
    with pytest.raises(DocxArchiveError) as caught:
        parse_docx(bomb, source_id=SOURCE)
    assert not hasattr(caught.value, "fragments")


def test_bytes_that_are_not_a_zip_are_refused_with_a_visible_error():
    with pytest.raises(DocxArchiveError, match="not a ZIP container"):
        parse_docx_bytes(b"this is not a document", source_id=SOURCE)


def test_a_zip_without_the_parts_of_a_document_is_refused(tmp_path):
    """Caught by the archive check, before python-docx is ever asked to open it."""
    import io
    import zipfile

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("hello.txt", "hello")
    with pytest.raises(DocxArchiveError, match="missing"):
        parse_docx_bytes(buffer.getvalue(), source_id=SOURCE)


def test_a_good_document_passes_the_same_limits_it_is_meant_to_pass():
    payload = fixture_path("basic.docx").read_bytes()
    from_path = parse_docx_bytes(payload, source_id=SOURCE)
    from_disk = parse_docx(fixture_path("basic.docx"), source_id=SOURCE)
    assert [f.text for f in from_path.fragments] == [f.text for f in from_disk.fragments]
    assert from_path.fragment_ids() == from_disk.fragment_ids()


# ================================================================== identity


def test_parsing_the_same_bytes_twice_produces_the_same_fragment_ids():
    """A re-parse must be recognisable as a re-parse, not a second document."""
    first = parse("basic.docx")
    second = parse("basic.docx")
    assert first.fragment_ids() == second.fragment_ids()
    assert len(set(first.fragment_ids())) == len(first.fragments)


def test_a_different_source_gets_different_fragment_ids():
    a = parse_docx(fixture_path("basic.docx"), source_id=uuid.uuid4())
    b = parse_docx(fixture_path("basic.docx"), source_id=uuid.uuid4())
    assert a.fragment_ids() != b.fragment_ids()


def test_ordinals_are_dense_and_ordered():
    result = parse("basic.docx")
    assert [f.ordinal for f in result.fragments] == list(range(len(result.fragments)))


def test_a_single_part_that_expands_a_thousandfold_is_refused_even_when_the_archive_does_not(
    tmp_path,
):
    """The per-part ratio check, proved on its own.

    The archive here expands to about 5:1 overall, so the whole-container check
    is quiet and only the per-part check can refuse it. Without a test like this
    one the per-part check could be deleted and every other test would still
    pass — redundancy that nobody has checked is not redundancy, it is an
    assumption.
    """
    padding = tmp_path / "padding.docx"
    padding.write_bytes(_zip_with_a_huge_part(with_incompressible_padding=True))

    import zipfile

    with zipfile.ZipFile(padding) as archive:
        infos = archive.infolist()
    total = sum(i.file_size for i in infos)
    compressed = sum(i.compress_size for i in infos)
    assert total / max(compressed, 1) < 50, "the container as a whole must look innocent"

    with pytest.raises(DocxArchiveError, match=r"expands \d+(\.\d+)?:1") as caught:
        parse_docx(padding, source_id=SOURCE)
    assert "word/document.xml" in str(caught.value), "the refusal must name the part"


# ------------------------------------------------------------ zip bomb helpers


def _zip_with_a_huge_part(with_incompressible_padding: bool = False) -> bytes:
    """A real package whose ``document.xml`` part is a deflate bomb.

    With ``with_incompressible_padding`` a 10 MiB member is added *stored*, which
    costs the overall ratio nothing (a stored part is already at 1:1) and so
    leaves the per-part check as the only thing that can object.
    """
    import io
    import zipfile

    from docx import Document as _Document

    document = _Document()
    document.add_paragraph("x" * 200_000)
    base = io.BytesIO()
    document.save(base)
    with zipfile.ZipFile(io.BytesIO(base.getvalue())) as original:
        members = {n: original.read(n) for n in original.namelist()}
    members["word/document.xml"] = b"<w:document>" + b"<!--" + b"\0" * 40_000_000 + b"-->"
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as out:
        for name, payload in members.items():
            out.writestr(name, payload)
        if with_incompressible_padding:
            out.writestr("word/padding.bin", b"\0" * 10_000_000, compress_type=zipfile.ZIP_STORED)
    return buffer.getvalue()


def _zip_with_many_parts(count: int) -> bytes:
    import io
    import zipfile

    from docx import Document as _Document

    document = _Document()
    document.add_paragraph("hello")
    base = io.BytesIO()
    document.save(base)
    with zipfile.ZipFile(io.BytesIO(base.getvalue())) as original:
        members = {n: original.read(n) for n in original.namelist()}
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as out:
        for name, payload in members.items():
            out.writestr(name, payload)
        for index in range(count):
            out.writestr(f"word/padding{index}.xml", "<x/>")
    return buffer.getvalue()


def _zip_without_document_xml() -> bytes:
    import io
    import zipfile

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as out:
        out.writestr("[Content_Types].xml", "<Types/>")
    return buffer.getvalue()


def _zip_with_a_traversing_member() -> bytes:
    import io
    import zipfile

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as out:
        out.writestr("[Content_Types].xml", "<Types/>")
        out.writestr("word/document.xml", "<document/>")
        out.writestr("../../etc/passwd", "root::0:0:::/:/bin/sh")
    return buffer.getvalue()
