"""C11 — EPUB parsing: no pages, ever (no database).

An EPUB has no pages, so the risk in this format is not a mislabelled page but
an invented one. Every fixture here is synthetic and generated by
``epub_fixtures`` in this same directory; ``booklet.epub`` even contains a
paragraph whose text says "page 12 of a paperback edition", so that a parser
which lifted a number out of the prose would be caught.

The container is read by **EbookLib** (``kb.catalog.parsers.epub``,
``PARSER_VERSION``); XHTML bodies are turned into ordered text blocks by the
standard library's ``html.parser``. No OCR: ``scan.epub`` is images only and
must come back ``needs_ocr`` with nothing written down.
"""

from __future__ import annotations

import uuid
from pathlib import Path

import ebooklib
import epub_fixtures as fx
import pytest

from kb.catalog.parsers.epub import (
    PARSER_NAME,
    PARSER_VERSION,
    fragment_row,
    parse_epub,
    text_at_locator,
    text_blocks,
)
from kb.contracts.entities import Locator
from kb.contracts.enums import LocatorKind, ProcessingStatus

pytestmark = pytest.mark.integration

ROOT = Path(__file__).resolve().parents[3]
COMMITTED = ROOT / "evals" / "fixtures" / "books"

SOURCE_ID = uuid.UUID("00000000-0000-4000-8000-0000000000c2")


def test_the_parser_is_a_real_library_and_says_which_one():
    assert PARSER_NAME == "ebooklib"
    assert PARSER_VERSION == ".".join(str(p) for p in ebooklib.VERSION)
    assert parse_epub(fx.booklet_epub(), source_id=SOURCE_ID).spine_documents == 3


# ------------------------------------------------------------- no invented pages


def test_no_epub_fragment_ever_carries_a_page():
    """Acceptance 2: an EPUB does not get invented pages.

    Checked on every fragment, including the one whose text literally says
    "page 12" — the number is in the prose, not in the structure, and must stay
    there.
    """
    result = parse_epub(fx.booklet_epub(), source_id=SOURCE_ID)
    assert result.fragments
    for fragment in result.fragments:
        assert fragment.locator.file_page is None
        assert fragment.locator.printed_label is None
        assert fragment.locator.kind is LocatorKind.EPUB_CHAPTER

    said_page_twelve = [f for f in result.fragments if "page 12" in f.text]
    assert len(said_page_twelve) == 1
    assert said_page_twelve[0].locator.file_page is None


def test_no_epub_fragment_uses_a_pdf_locator_kind():
    result = parse_epub(fx.booklet_epub(), source_id=SOURCE_ID)
    kinds = {f.locator.kind for f in result.fragments}
    assert kinds == {LocatorKind.EPUB_CHAPTER}
    assert not (kinds & {LocatorKind.PDF_FILE_PAGE, LocatorKind.PDF_PRINTED_LABEL})


# ------------------------------------------------------------- spine and chapter


def test_the_spine_position_is_the_position_in_the_reading_order():
    result = parse_epub(fx.booklet_epub(), source_id=SOURCE_ID)
    positions = [f.locator.spine for f in result.fragments]
    assert positions == ["1", "1", "2", "2", "2", "2", "2", "3", "3", "3", "3", "3", "3", "3"]
    assert all(isinstance(p, str) and p.isdigit() for p in positions)


def test_a_chapter_title_is_the_one_the_books_own_contents_states():
    result = parse_epub(fx.booklet_epub(), source_id=SOURCE_ID)
    by_spine: dict[str, set[str | None]] = {}
    for fragment in result.fragments:
        by_spine.setdefault(str(fragment.locator.spine), set()).add(fragment.locator.chapter)
    assert by_spine == {"1": {"Cover"}, "2": {"Chapter One"}, "3": {"Chapter Two"}}


def test_a_chapter_the_contents_does_not_name_is_none_and_not_invented():
    """The trap: a document with no TOC entry must not borrow a neighbour's name."""
    nav_without_ch2 = fx.NAV_XHTML.replace('<li><a href="ch2.xhtml#start">Chapter Two</a></li>', "")
    result = parse_epub(fx.booklet_epub_with_nav(nav_without_ch2), source_id=SOURCE_ID)

    by_spine: dict[str, set[str | None]] = {}
    for fragment in result.fragments:
        by_spine.setdefault(str(fragment.locator.spine), set()).add(fragment.locator.chapter)
    assert by_spine == {"1": {"Cover"}, "2": {"Chapter One"}, "3": {None}}
    # the text of the unnamed document is still there — only the title is unknown
    assert any(f.text == "The last chapter of the synthetic booklet." for f in result.fragments)


def test_a_contents_entry_without_a_title_yields_no_chapter_at_all():
    nav_without_titles = fx.NAV_XHTML.replace(">Cover<", "><").replace(">Chapter One<", "><")
    nav_without_titles = nav_without_titles.replace(">Chapter Two<", "><")
    result = parse_epub(fx.booklet_epub_with_nav(nav_without_titles), source_id=SOURCE_ID)
    assert {f.locator.chapter for f in result.fragments} == {None}
    assert len(result.fragments) == 14


# ------------------------------------------------------------------- paragraphs


def test_paragraph_numbers_restart_in_each_document_and_run_without_gaps():
    result = parse_epub(fx.booklet_epub(), source_id=SOURCE_ID)
    by_spine: dict[str, list[int]] = {}
    for fragment in result.fragments:
        by_spine.setdefault(str(fragment.locator.spine), []).append(fragment.locator.paragraph)
    assert by_spine == {"1": [1, 2], "2": [1, 2, 3, 4, 5], "3": [1, 2, 3, 4, 5, 6, 7]}


def test_ordinals_are_unique_and_follow_the_reading_order():
    result = parse_epub(fx.booklet_epub(), source_id=SOURCE_ID)
    assert [f.ordinal for f in result.fragments] == list(range(len(result.fragments)))
    assert len({f.id for f in result.fragments}) == len(result.fragments)
    # cover, then chapter one, then chapter two
    assert [f.text for f in result.fragments][:2] == [
        "A Synthetic Booklet",
        "Every byte of this file was written by a test.",
    ]


def test_the_blocks_of_a_document_are_the_blocks_that_document_contains():
    result = parse_epub(fx.booklet_epub(), source_id=SOURCE_ID)
    chapter_one = [f.text for f in result.fragments if f.locator.spine == "2"]
    assert chapter_one == [
        "Chapter One",
        "A paragraph that exists only in this synthetic book.",
        "A second paragraph, with inline emphasis inside it.",
        "First item of a list",
        "Second item of a list",
    ]


def test_a_table_cell_is_its_own_block():
    result = parse_epub(fx.booklet_epub(), source_id=SOURCE_ID)
    cells = [f.text for f in result.fragments if f.text.startswith("Cell ")]
    assert cells == ["Cell A1", "Cell A2", "Cell B1", "Cell B2"]


# ------------------------------------------------------------ opening by locator


def test_a_source_opens_by_spine_and_paragraph():
    data = fx.booklet_epub()
    result = parse_epub(data, source_id=SOURCE_ID)
    target = result.fragments[3]
    assert target.locator.spine == "2" and target.locator.paragraph == 2

    opened = text_at_locator(data, target.locator)
    assert opened == target.text
    assert opened == "A paragraph that exists only in this synthetic book."


def test_a_locator_that_names_nothing_returns_none():
    data = fx.booklet_epub()
    assert (
        text_at_locator(data, Locator(kind=LocatorKind.EPUB_CHAPTER, spine="2", paragraph=99))
        is None
    )
    assert text_at_locator(data, Locator(kind=LocatorKind.EPUB_CHAPTER, spine="9")) is None
    assert (
        text_at_locator(data, Locator(kind=LocatorKind.EPUB_CHAPTER, spine="front", paragraph=1))
        is None
    )
    assert text_at_locator(data, Locator(kind=LocatorKind.EPUB_CHAPTER, spine="0")) is None
    # a PDF locator is not an EPUB locator, and is not reinterpreted as one
    assert text_at_locator(data, Locator(kind=LocatorKind.PDF_FILE_PAGE, file_page=1)) is None


# -------------------------------------------------------------- the text layer


def test_a_book_of_images_becomes_needs_ocr_and_not_invented_text():
    result = parse_epub(fx.scan_epub(), source_id=SOURCE_ID)

    assert result.processing is ProcessingStatus.NEEDS_OCR
    assert result.needs_ocr is True
    assert result.fragments == ()
    assert result.spine_documents == 1  # the document was read, it held no text
    assert [(p.code, p.spine) for p in result.problems] == [("no_text_in_spine_item", "1")]
    assert "OCR" in result.problems[0].detail
    assert [fragment_row(f) for f in result.fragments] == []


def test_a_document_the_manifest_does_not_define_is_reported_not_skipped():
    """A spine entry pointing at a missing manifest id is a visible problem."""
    opf = fx.CONTENT_OPF.format(title="A Synthetic Booklet", creator="").replace(
        '<itemref idref="ch2"/>', '<itemref idref="ch2"/><itemref idref="ghost"/>'
    )
    data = fx.container_with(
        opf=opf,
        nav=fx.NAV_XHTML,
        documents={
            "cover.xhtml": fx.COVER_XHTML,
            "ch1.xhtml": fx.CH1_XHTML,
            "ch2.xhtml": fx.CH2_XHTML,
        },
    )
    result = parse_epub(data, source_id=SOURCE_ID)
    assert [p.code for p in result.problems] == ["missing_spine_item"]
    assert result.problems[0].spine == "4"
    assert result.processing is ProcessingStatus.PARTIAL  # three documents read, one not
    assert len(result.fragments) == 14


# ---------------------------------------------------------------- visible errors


def test_a_file_that_is_not_an_epub_fails_visibly():
    result = parse_epub(fx.damaged_epub(), source_id=SOURCE_ID)
    assert result.processing is ProcessingStatus.FAILED
    assert result.fragments == ()
    assert [p.code for p in result.problems] == ["unreadable_epub"]
    assert "EbookLib" in result.problems[0].detail


def test_a_package_with_an_empty_spine_fails_rather_than_claiming_a_scan():
    data = fx.container_with(
        opf=fx.SCAN_OPF.replace('<itemref idref="scan"/>', ""),
        nav=fx.SCAN_NAV_XHTML,
        documents={
            "scan.xhtml": fx.SCAN_XHTML,
            "plate.png": b"\x89PNG\r\n\x1a\n" + b"\x00" * 16,
        },
    )
    result = parse_epub(data, source_id=SOURCE_ID)
    assert result.processing is ProcessingStatus.FAILED
    assert [p.code for p in result.problems] == ["empty_spine"]
    assert result.fragments == ()


# ------------------------------------------------------------------ provenance


def test_a_creator_is_read_when_the_package_states_one_and_never_invented():
    assert parse_epub(fx.booklet_epub(), source_id=SOURCE_ID).author == "Ada Fixture"
    assert parse_epub(fx.anonymous_epub(), source_id=SOURCE_ID).author is None
    assert parse_epub(fx.scan_epub(), source_id=SOURCE_ID).author is None


def test_a_title_is_read_when_the_package_states_one():
    assert parse_epub(fx.booklet_epub(), source_id=SOURCE_ID).title == "A Synthetic Booklet"
    assert parse_epub(fx.damaged_epub(), source_id=SOURCE_ID).title is None


def test_the_fragment_row_carries_the_columns_the_table_has():
    row = fragment_row(parse_epub(fx.booklet_epub(), source_id=SOURCE_ID).fragments[0])
    assert row == {
        "id": row["id"],
        "source_id": SOURCE_ID,
        "ordinal": 0,
        "locator_kind": "epub_chapter",
        "file_page": None,
        "printed_label": None,
        "chapter": "Cover",
        "paragraph": 1,
        "text": "A Synthetic Booklet",
    }
    # the spine position has no column in kb.fragment; see the module docstring
    # and the finding reported to the DDL owner.
    assert "spine" not in row


# ------------------------------------------------------------- block extraction


@pytest.mark.parametrize(
    ("markup", "expected"),
    [
        ("<p>one</p><p>two</p>", ("one", "two")),
        ("<p>one<p>two", ("one", "two")),  # unclosed: still two blocks, in order
        ("<p>a <em>b</em> c</p>", ("a b c",)),
        ("<p>a &amp; b</p>", ("a & b",)),
        ("<p>  spaced   out  </p>", ("spaced out",)),
        ("<p></p><p>  </p><p>real</p>", ("real",)),  # layout whitespace is not text
        (
            "<head><title>Doc title</title></head><body><p>body</p></body>",
            ("body",),
        ),  # the document title is metadata, not the book
        (
            '<nav epub:type="toc"><ol><li><a href="a.xhtml">Chapter</a></li></ol></nav><p>body</p>',
            ("body",),
        ),  # the contents page is not a chapter of the book
        ("<ul><li>one</li><li>two</li></ul>", ("one", "two")),
        ("<table><tr><td>a</td><td>b</td></tr></table>", ("a", "b")),  # cells stay cells
        ('<p><img src="plate.png" alt="a scanned plate"/></p><p>after</p>', ("after",)),
    ],
)
def test_text_blocks_pulls_out_the_text_and_nothing_else(markup, expected):
    assert text_blocks(markup) == expected


# -------------------------------------------------------------------- fixtures


def test_the_committed_fixtures_are_exactly_what_this_module_generates():
    for name, expected in fx.all_fixtures().items():
        committed = COMMITTED / name
        assert committed.exists(), f"{name} is missing from evals/fixtures/books/"
        assert committed.read_bytes() == expected, f"{name} drifted from its generator"
