"""C11 — PDF parsing: a file page is not a printed label (no database).

Every fixture is synthetic and generated by ``pdf_fixtures`` in this same
directory. None of them is a real book and none was downloaded: a downloaded
fixture could only be asserted against, never about — no test here could say
*which* file page carries *which* printed label if the bytes were somebody
else's.

The library under test is **pypdf** (imported by ``kb.catalog.parsers.pdf``,
version recorded in that module's ``PARSER_VERSION``). It is a real parse of
real bytes. There is no OCR in this card, and
``test_no_ocr_library_is_imported_by_the_parser`` proves that structurally
rather than asserting it in a comment.
"""

from __future__ import annotations

import ast
import io
import uuid
from pathlib import Path

import pdf_fixtures as fx
import pypdf
import pytest

from kb.catalog.parsers.pdf import (
    PARSER_NAME,
    PARSER_VERSION,
    fragment_row,
    parse_pdf,
    text_at_locator,
)
from kb.contracts.entities import Locator
from kb.contracts.enums import LocatorKind, ProcessingStatus

pytestmark = pytest.mark.integration

ROOT = Path(__file__).resolve().parents[3]
PARSER_SOURCE = ROOT / "src" / "kb" / "catalog" / "parsers" / "pdf.py"
COMMITTED = ROOT / "evals" / "fixtures" / "books"

SOURCE_ID = uuid.UUID("00000000-0000-4000-8000-0000000000c1")


# ------------------------------------------------- the two columns, kept apart


def test_the_parser_is_a_real_library_and_says_which_one():
    assert PARSER_NAME == "pypdf"
    assert PARSER_VERSION == pypdf.__version__
    # and the fixture really is parsed by that library, not by a stand-in
    reader = pypdf.PdfReader(io.BytesIO(fx.text_book_pdf()))
    assert len(reader.pages) == 4


def test_a_file_page_and_the_printed_label_on_it_are_different_values():
    """The invariant, stated as a test.

    ``text_book.pdf`` declares /PageLabels: file pages 1-2 are 'i','ii' and
    file pages 3-4 are '1','2'. File page 3 is printed page 1. Both numbers are
    real, both were read, and neither was derived from the other.
    """
    result = parse_pdf(fx.text_book_pdf(), source_id=SOURCE_ID)

    pairs = [(f.locator.file_page, f.locator.printed_label) for f in result.fragments]
    assert pairs == [(1, "i"), (2, "ii"), (3, "1"), (4, "2")]


def test_a_printed_label_is_never_copied_out_of_the_file_page_column():
    result = parse_pdf(fx.text_book_pdf(), source_id=SOURCE_ID)
    for fragment in result.fragments:
        assert fragment.locator.printed_label != str(fragment.locator.file_page)
    # the difference is real, not a coincidence of the fixture
    assert len({f.locator.file_page for f in result.fragments}) == 4
    assert len({f.locator.printed_label for f in result.fragments}) == 4


def test_a_document_that_declares_no_labels_gets_no_labels():
    """pypdf answers the page number when a document declares nothing.

    ``authored.pdf`` has no /PageLabels tree, so pypdf's own answer for its one
    page would be "1" — the file page wearing a label's clothes. Recording it
    would make the printed_label column corroborate file_page and hide exactly
    the disagreement the column exists to keep.
    """
    result = parse_pdf(fx.authored_pdf(), source_id=SOURCE_ID)
    assert [f.locator.file_page for f in result.fragments] == [1]
    assert [f.locator.printed_label for f in result.fragments] == [None]
    # pypdf really would have said "1" — the value was available and dropped
    reader = pypdf.PdfReader(io.BytesIO(fx.authored_pdf()))
    assert reader.page_labels == ["1"]


def test_every_pdf_fragment_is_a_file_page_and_nothing_else():
    result = parse_pdf(fx.text_book_pdf(), source_id=SOURCE_ID)
    for fragment in result.fragments:
        assert fragment.locator.kind is LocatorKind.PDF_FILE_PAGE
        assert fragment.locator.file_page is not None
        assert fragment.locator.chapter is None
        assert fragment.locator.paragraph is None


def test_the_ordinal_is_the_position_of_the_page_in_the_file():
    result = parse_pdf(fx.text_book_pdf(), source_id=SOURCE_ID)
    assert [f.ordinal for f in result.fragments] == [0, 1, 2, 3]
    assert [f.ordinal + 1 for f in result.fragments] == [
        f.locator.file_page for f in result.fragments
    ]


# --------------------------------------------------------- opening by locator


def test_a_source_opens_by_its_file_page():
    data = fx.text_book_pdf()
    result = parse_pdf(data, source_id=SOURCE_ID)
    page_three = result.fragments[2]

    opened = text_at_locator(data, page_three.locator)
    assert opened == page_three.text
    assert opened is not None
    assert opened.startswith("Chapter one begins on the page printed as 1")


def test_a_source_opens_by_its_printed_label_too():
    """Printed label "1" is file page 3 — the two must not be interchangeable."""
    data = fx.text_book_pdf()
    by_label = text_at_locator(data, Locator(kind=LocatorKind.PDF_PRINTED_LABEL, printed_label="1"))
    by_page = text_at_locator(data, Locator(kind=LocatorKind.PDF_FILE_PAGE, file_page=1))
    assert by_label is not None and by_page is not None
    assert by_label != by_page
    assert by_label.startswith("Chapter one begins")


def test_a_locator_that_names_nothing_returns_none():
    data = fx.text_book_pdf()
    assert text_at_locator(data, Locator(kind=LocatorKind.PDF_FILE_PAGE, file_page=99)) is None
    assert (
        text_at_locator(data, Locator(kind=LocatorKind.PDF_PRINTED_LABEL, printed_label="nope"))
        is None
    )
    assert (
        text_at_locator(data, Locator(kind=LocatorKind.PDF_PRINTED_LABEL, printed_label="")) is None
    )
    # an EPUB locator is not a PDF locator, and is not quietly reinterpreted
    assert text_at_locator(data, Locator(kind=LocatorKind.EPUB_CHAPTER, paragraph=1)) is None


def test_a_printed_label_several_pages_share_is_not_guessed():
    """Two pages labelled "A": answering either one would be a coin flip."""
    data = fx.build_pdf(
        [fx.PdfPage(lines=[f"page {n}"]) for n in range(1, 5)],
        page_labels=[
            fx.PageLabelRange(start=0, style="/A", first=1),
            fx.PageLabelRange(start=3, style="/A", first=1),
        ],
    )
    result = parse_pdf(data, source_id=SOURCE_ID)
    assert [(f.locator.file_page, f.locator.printed_label) for f in result.fragments] == [
        (1, "A"),
        (2, "B"),
        (3, "C"),
        (4, "A"),
    ]
    assert (
        text_at_locator(data, Locator(kind=LocatorKind.PDF_PRINTED_LABEL, printed_label="A"))
        is None
    )
    # an unambiguous label on the same file still resolves
    assert (
        text_at_locator(data, Locator(kind=LocatorKind.PDF_PRINTED_LABEL, printed_label="B"))
        == "page 2"
    )


# ------------------------------------------------------------- the text layer


def test_the_text_is_the_text_that_is_on_that_page():
    result = parse_pdf(fx.text_book_pdf(), source_id=SOURCE_ID)
    assert [f.text for f in result.fragments] == [
        "Title page of a synthetic book\nno author is written here",
        "Contents\nIntroduction .... 1",
        "Chapter one begins on the page printed as 1\nsecond line",
        "Chapter one continues on the page printed as 2",
    ]


def test_a_page_less_scan_becomes_needs_ocr_and_not_invented_text():
    """The card's central promise, on a real file with no text layer.

    ``scan.pdf`` draws a 2x2 grey image on each of its two pages and issues no
    text-drawing operator at all. There is no text in it, so none is produced:
    the result carries zero fragments, and the reason is visible per page.
    """
    result = parse_pdf(fx.scan_pdf(), source_id=SOURCE_ID)

    assert result.processing is ProcessingStatus.NEEDS_OCR
    assert result.needs_ocr is True
    assert result.fragments == ()
    assert result.page_count == 2  # the pages were counted, not skipped
    assert [(p.code, p.file_page) for p in result.problems] == [
        ("no_text_layer", 1),
        ("no_text_layer", 2),
    ]
    assert all("OCR" in p.detail for p in result.problems)
    # nothing anywhere in the result pretends to be the book's text
    assert not any(f.text for f in result.fragments)
    assert "A Scan" not in "".join(p.detail for p in result.problems)


def test_a_scan_page_never_becomes_a_fragment_row():
    """The database-facing half of the same promise, without a database.

    ``fragment_row`` is the only mapping this card offers to a caller, and on
    an empty result it can only produce nothing.
    """
    result = parse_pdf(fx.scan_pdf(), source_id=SOURCE_ID)
    assert [fragment_row(f) for f in result.fragments] == []


def test_a_half_scanned_document_is_partial_and_says_which_page_is_missing():
    data = fx.build_pdf(
        [
            fx.PdfPage(lines=["typed page one"]),
            fx.PdfPage(image=True),
            fx.PdfPage(lines=["typed page three"]),
        ],
        page_labels=[fx.PageLabelRange(start=0, style="/D", first=1)],
    )
    result = parse_pdf(data, source_id=SOURCE_ID)

    assert result.processing is ProcessingStatus.PARTIAL
    assert [f.locator.file_page for f in result.fragments] == [1, 3]
    assert [f.ordinal for f in result.fragments] == [0, 2]  # ordinals keep the page positions
    assert [(p.code, p.file_page) for p in result.problems] == [("no_text_layer", 2)]
    assert "image" in result.problems[0].detail


def test_no_ocr_library_is_imported_by_the_parser():
    """OCR is not implemented, and none is faked.

    An import walk of the parser module: no OCR/vision package is named, and the
    only third-party import is pypdf. This is the check that would fail if a
    later change quietly wired a "text extraction" fallback that guesses.
    """
    tree = ast.parse(PARSER_SOURCE.read_text(encoding="utf-8"))
    imported: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            imported.add(node.module.split(".")[0])

    assert "pypdf" in imported
    assert not (imported & {"pytesseract", "tesserocr", "easyocr", "paddleocr", "ocrmypdf"})
    assert "fitz" not in imported and "pymupdf" not in imported

    # Call-shaped needles for the APIs an OCR package would be used through.
    # The first version of this test also banned the bare text "ocr(", which
    # failed on this module's own ``needs_ocr`` property — a textual ban wide
    # enough to hit a status name proves nothing about OCR.
    banned = ("image_to_string", "run_and_get_output", "do_ocr", "ocr_image", "tesseract")
    source = PARSER_SOURCE.read_text(encoding="utf-8").lower()
    for needle in banned:
        assert needle not in source, f"{needle!r} appears in the parser source"


# ------------------------------------------------------------- visible errors


def test_a_file_that_is_not_a_pdf_fails_visibly():
    result = parse_pdf(fx.broken_pdf(), source_id=SOURCE_ID)
    assert result.processing is ProcessingStatus.FAILED
    assert result.fragments == ()
    assert [p.code for p in result.problems] == ["unreadable_pdf"]
    assert "pypdf" in result.problems[0].detail


def test_a_truncated_pdf_fails_visibly():
    result = parse_pdf(fx.truncated_pdf(), source_id=SOURCE_ID)
    assert result.processing is ProcessingStatus.FAILED
    assert result.fragments == ()
    assert [p.code for p in result.problems] == ["unreadable_pdf"]


def test_a_pdf_with_no_pages_fails_rather_than_claiming_a_scan():
    data = fx.build_pdf([])
    result = parse_pdf(data, source_id=SOURCE_ID)
    assert result.processing is ProcessingStatus.FAILED
    assert [p.code for p in result.problems] == ["no_pages"]
    assert result.fragments == ()


def test_an_encrypted_pdf_is_refused_rather_than_guessed():
    """Encrypted with pypdf's own writer — a real encrypted file, not a flag."""
    reader = pypdf.PdfReader(io.BytesIO(fx.authored_pdf()))
    writer = pypdf.PdfWriter()
    writer.append(reader)
    # S106: this is a password for a file this test builds itself, in a
    # temporary buffer that no password manager and no service ever sees. It
    # is a fixture value, not a credential, and it is inline on purpose so the
    # test says exactly what password the file was sealed with.
    writer.encrypt(user_password="not-empty", owner_password="not-empty")  # noqa: S106
    buffer = io.BytesIO()
    writer.write(buffer)

    result = parse_pdf(buffer.getvalue(), source_id=SOURCE_ID)
    assert result.processing is ProcessingStatus.FAILED
    assert [p.code for p in result.problems] == ["encrypted_pdf"]
    assert result.fragments == ()
    assert "guessed" in result.problems[0].detail


# ------------------------------------------------------------------ provenance


def test_an_author_is_read_when_the_file_states_one_and_never_invented():
    assert parse_pdf(fx.authored_pdf(), source_id=SOURCE_ID).author == "Ada Fixture"
    assert parse_pdf(fx.text_book_pdf(), source_id=SOURCE_ID).author is None
    assert parse_pdf(fx.scan_pdf(), source_id=SOURCE_ID).author is None


def test_a_title_is_read_when_the_file_states_one():
    assert parse_pdf(fx.text_book_pdf(), source_id=SOURCE_ID).title == (
        "A Synthetic Book About Locators"
    )
    assert parse_pdf(fx.broken_pdf(), source_id=SOURCE_ID).title is None


def test_the_fragment_row_carries_every_locator_column():
    row = fragment_row(parse_pdf(fx.text_book_pdf(), source_id=SOURCE_ID).fragments[2])
    assert row == {
        "id": row["id"],
        "source_id": SOURCE_ID,
        "ordinal": 2,
        "locator_kind": "pdf_file_page",
        "file_page": 3,
        "printed_label": "1",
        "chapter": None,
        "paragraph": None,
        "text": "Chapter one begins on the page printed as 1\nsecond line",
    }


# -------------------------------------------------------------------- fixtures


def test_the_committed_fixtures_are_exactly_what_this_module_generates():
    """The bytes under evals/ are synthetic and reproducible, or they are wrong."""
    for name, expected in fx.all_fixtures().items():
        committed = COMMITTED / name
        assert committed.exists(), f"{name} is missing from evals/fixtures/books/"
        assert committed.read_bytes() == expected, f"{name} drifted from its generator"


def test_the_synthetic_fixtures_are_never_referenced_by_the_product():
    """Acceptance: synthetic files are not preloaded into production.

    Nothing under src/, migrations/ or deploy/ may name the fixture directory
    or any committed fixture file. If a future card ships a preloaded book,
    this fails.
    """
    needles = ("evals/fixtures", "text_book.pdf", "scan.pdf", "booklet.epub", "scan.epub")
    for folder in ("src", "migrations", "deploy"):
        for path in (ROOT / folder).rglob("*"):
            if not path.is_file():
                continue
            body = path.read_text(encoding="utf-8", errors="ignore")
            for needle in needles:
                assert needle not in body, f"{path} references {needle}"
