"""Synthetic PDF fixtures for card C11. Generated here, byte for byte.

Nothing in this file is a real book. A PDF is written by hand — objects, a
cross-reference table and a trailer — so that the parser under test is handed
a document whose every property is known in advance and can be asserted
against. A fixture that were downloaded could only be asserted against: no
test could say *which* page holds *which* label, and a fixture that changes
under a proxy would change the assertions.

Three properties of the generated documents matter:

* ``text_book.pdf`` declares a ``/PageLabels`` number tree, so file page 3
  carries the printed label ``"1"``. That disagreement between the two columns
  is the whole point of the card, so the fixture is built to contain it.
* ``authored.pdf`` carries ``/Author`` in its document info; the other two do
  not. An author that is not in the file must come back ``None``.
* ``scan.pdf`` has no text-drawing operator on any page — it draws a 2x2 grey
  image instead. It is what a page of a scanned book looks like to a text
  extractor, and it must come back ``needs_ocr`` with no fragments.

The generated bytes are also committed under ``evals/fixtures/books/`` and a
test asserts the committed file is identical to what this module builds, so the
two can never drift.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

# Two grey pixels, uncompressed. /DeviceGray /BitsPerComponent 8 -> 2 bytes per
# row, 2 rows.
SCAN_PIXELS = b"\x80\x80\x80\x80"


@dataclass
class PdfPage:
    """One page to draw. ``lines`` empty and ``image`` true = a scan page."""

    lines: list[str] = field(default_factory=list)
    image: bool = False


@dataclass
class PageLabelRange:
    """One entry of the ``/PageLabels`` number tree: from ``start`` page index."""

    start: int
    style: str  # /D decimal, /r lower roman, /R upper roman
    first: int = 1
    prefix: str = ""


class _Builder:
    """Assembles numbered objects and remembers each one's byte offset."""

    def __init__(self) -> None:
        self._objects: dict[int, bytes] = {}

    def add(self, number: int, body: bytes) -> None:
        self._objects[number] = body

    def build(self, root: int, info: int | None) -> bytes:
        out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
        offsets: dict[int, int] = {}
        for number in sorted(self._objects):
            offsets[number] = len(out)
            out += f"{number} 0 obj\n".encode()
            out += self._objects[number]
            out += b"\nendobj\n"

        xref_at = len(out)
        highest = max(self._objects) + 1
        out += f"xref\n0 {highest}\n".encode()
        out += b"0000000000 65535 f \n"
        for number in range(1, highest):
            if number in offsets:
                out += f"{offsets[number]:010d} 00000 n \n".encode()
            else:
                out += b"0000000000 00000 f \n"
        trailer = f"<< /Size {highest} /Root {root} 0 R"
        if info is not None:
            trailer += f" /Info {info} 0 R"
        trailer += " >>"
        out += b"trailer\n" + trailer.encode() + b"\n"
        out += f"startxref\n{xref_at}\n%%EOF\n".encode()
        return bytes(out)


def _pdf_string(value: str) -> bytes:
    escaped = value.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
    return b"(" + escaped.encode("latin-1") + b")"


def _text_stream(lines: list[str]) -> bytes:
    parts = [b"BT", b"/F1 12 Tf", b"14 TL", b"20 160 Td"]
    for index, line in enumerate(lines):
        if index:
            parts.append(b"T*")
        parts.append(_pdf_string(line) + b" Tj")
    parts.append(b"ET")
    return b"\n".join(parts) + b"\n"


def _image_stream() -> bytes:
    return b"q\n180 0 0 180 20 20 cm\n/Im1 Do\nQ\n"


def _stream_object(body: bytes) -> bytes:
    return b"<< /Length " + str(len(body)).encode() + b" >>\nstream\n" + body + b"endstream"


def build_pdf(
    pages: list[PdfPage],
    *,
    info: dict[str, str] | None = None,
    page_labels: list[PageLabelRange] | None = None,
) -> bytes:
    """A valid PDF containing exactly the pages and labels described."""
    builder = _Builder()
    page_count = len(pages)
    catalog_no, pages_no, font_no, info_no = 1, 2, 3, 4
    first_page_no = 5
    image_no = first_page_no + 2 * page_count  # after every page + its stream

    kid_numbers = [first_page_no + 2 * i for i in range(page_count)]
    builder.add(
        pages_no,
        b"<< /Type /Pages /Count "
        + str(page_count).encode()
        + b" /Kids ["
        + b" ".join(f"{n} 0 R".encode() for n in kid_numbers)
        + b"] >>",
    )
    builder.add(font_no, b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    needs_image = any(p.image for p in pages)
    catalog = f"<< /Type /Catalog /Pages {pages_no} 0 R".encode()
    if page_labels:
        nums: list[bytes] = []
        for entry in page_labels:
            label_dict = (
                f"<< /S {entry.style} /St {entry.first} /P {_pdf_string(entry.prefix).decode()}"
            )
            label_dict += " >>"
            nums += [str(entry.start).encode(), label_dict.encode()]
        catalog += b" /PageLabels << /Nums [" + b" ".join(nums) + b"] >>"
    catalog += b" >>"
    builder.add(catalog_no, catalog)

    if needs_image:
        builder.add(
            image_no,
            b"<< /Type /XObject /Subtype /Image /Width 2 /Height 2 /ColorSpace "
            b"/DeviceGray /BitsPerComponent 8 /Length "
            + str(len(SCAN_PIXELS)).encode()
            + b" >>\nstream\n"
            + SCAN_PIXELS
            + b"\nendstream",
        )

    for index, page in enumerate(pages):
        page_no = first_page_no + 2 * index
        stream_no = page_no + 1
        resources = b"<< /Font << /F1 " + str(font_no).encode() + b" 0 R >>"
        if page.image:
            resources += b" /XObject << /Im1 " + str(image_no).encode() + b" 0 R >>"
        resources += b" >>"
        builder.add(
            page_no,
            b"<< /Type /Page /Parent "
            + str(pages_no).encode()
            + b" 0 R /MediaBox [0 0 200 200] /Resources "
            + resources
            + b" /Contents "
            + str(stream_no).encode()
            + b" 0 R >>",
        )
        body = _image_stream() if page.image else _text_stream(page.lines)
        builder.add(stream_no, _stream_object(body))

    info_no_used: int | None = None
    if info:
        entries: list[bytes] = []
        for key, value in info.items():
            entries += [f"/{key}".encode(), _pdf_string(value)]
        builder.add(info_no, b"<< " + b" ".join(entries) + b" >>")
        info_no_used = info_no

    return builder.build(catalog_no, info_no_used)


# --------------------------------------------------------- the three files


def text_book_pdf() -> bytes:
    """Four text pages whose printed labels disagree with their file pages.

    ``/PageLabels`` declares pages 0-1 as lower roman (``i``, ``ii``) and pages
    2-3 as decimal starting at 1 (``1``, ``2``). So file page 3 is printed
    page 1 — the classic front-matter offset, and the exact case a parser that
    "helpfully" copies the page position into the label column would get wrong.
    """
    return build_pdf(
        [
            PdfPage(lines=["Title page of a synthetic book", "no author is written here"]),
            PdfPage(lines=["Contents", "Introduction .... 1"]),
            PdfPage(lines=["Chapter one begins on the page printed as 1", "second line"]),
            PdfPage(lines=["Chapter one continues on the page printed as 2"]),
        ],
        info={"Title": "A Synthetic Book About Locators", "Producer": "kb-c11-fixture"},
        page_labels=[
            PageLabelRange(start=0, style="/r", first=1),
            PageLabelRange(start=2, style="/D", first=1),
        ],
    )


def authored_pdf() -> bytes:
    """One page, no page-label tree, and an author the file actually states."""
    return build_pdf(
        [PdfPage(lines=["A page written by someone the file names"])],
        info={"Title": "Attributed Synthetic Booklet", "Author": "Ada Fixture"},
    )


def scan_pdf() -> bytes:
    """Two pages that draw an image and no text at all."""
    return build_pdf([PdfPage(image=True), PdfPage(image=True)], info={"Title": "A Scan"})


def unknown_png_free_scan() -> bytes:
    """Alias kept for readability at the call site; see :func:`scan_pdf`."""
    return scan_pdf()


def broken_pdf() -> bytes:
    """Real bytes that are not a PDF — the 'unsupported file' case."""
    return b"this is not a pdf, it is a text file pretending to be one\n" * 4


def truncated_pdf() -> bytes:
    """A real PDF whose trailer was cut off mid-file."""
    good = authored_pdf()
    return good[: int(len(good) * 0.6)]


def all_fixtures() -> dict[str, Any]:
    """Every committed fixture, for the drift test in ``pdf_fixtures_test``."""
    return {
        "text_book.pdf": text_book_pdf(),
        "authored.pdf": authored_pdf(),
        "scan.pdf": scan_pdf(),
    }
